[workspace]

members = [
    "1-sonar-sweep",
    "2-dive",
    "3-binary-diagnostic",
    "4-giant-squid",
    "5-hydrothermal-vents",
    "6-lanternfish",
    "7-whale-treachery",
    "8-seven-segment-search",
    "9-smoke-basin",
    "10-syntax-scoring",
]
